rss_sources:
  - name: "YIMBY - Long Island City"
    url: "https://newyorkyimby.com/neighborhoods/long-island-city/feed"
    source: "YIMBY"
  - name: "YIMBY - Astoria"
    url: "https://newyorkyimby.com/neighborhoods/astoria/feed"
    source: "YIMBY"
  - name: "YIMBY - Flushing"
    url: "https://newyorkyimby.com/neighborhoods/flushing/feed"
    source: "YIMBY"
  - name: "YIMBY - Jamaica"
    url: "https://newyorkyimby.com/neighborhoods/jamaica/feed"
    source: "YIMBY"
  - name: "YIMBY - Ridgewood"
    url: "https://newyorkyimby.com/neighborhoods/ridgewood/feed"
    source: "YIMBY"
  - name: "YIMBY - Sunnyside"
    url: "https://newyorkyimby.com/neighborhoods/sunnyside/feed"
    source: "YIMBY"
  - name: "YIMBY - Woodside"
    url: "https://newyorkyimby.com/neighborhoods/woodside/feed"
    source: "YIMBY"
  - name: "YIMBY - Rego Park"
    url: "https://newyorkyimby.com/neighborhoods/rego-park/feed"
    source: "YIMBY"
  - name: "YIMBY - Forest Hills"
    url: "https://newyorkyimby.com/neighborhoods/forest-hills/feed"
    source: "YIMBY"
  - name: "YIMBY - Rockaway"
    url: "https://newyorkyimby.com/neighborhoods/rockaway-peninsula/feed"
    source: "YIMBY"

html_sources:
  - name: "TRD - New York"
    url: "https://therealdeal.com/new-york/"
    source: "TRD"
    list_selector: "article"
    title_selector: "h2, h3, a"
    link_selector: "a"
    date_selector: "time"
    summary_selector: "p"

  - name: "Commercial Observer - Home"
    url: "https://commercialobserver.com/"
    source: "Commercial Observer"
    list_selector: "article"
    title_selector: "h2, h3, a"
    link_selector: "a"
    date_selector: "time"
    summary_selector: "p"

  - name: "PincusCo - Home"
    url: "https://www.pincusco.com/"
    source: "PincusCo"
    list_selector: "article, .entry, .post, .card"
    title_selector: "h2, h3, a"
    link_selector: "a"
    date_selector: "time, .date"
    summary_selector: "p"

  - name: "CityRealty - Market Insight"
    url: "https://www.cityrealty.com/nyc/market-insight"
    source: "CityRealty"
    list_selector: "article, .article-item, .news-item"
    title_selector: "h2, h3, a"
    link_selector: "a"
    date_selector: "time, .date"
    summary_selector: "p, .summary"







